services:
  postgres:
    image: postgres:17
    container_name: blogify_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: blogify_dev
      POSTGRES_USER: blogify_user
      POSTGRES_PASSWORD: blogify_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blogify_user -d blogify_dev"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local 